source 'https://rubygems.org'

gem 'pry'
gem 'json'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sass'
gem 'coffee-script'
gem 'haml'
gem 'sinatra-asset-pipeline'
gem 'burgatron', github: 'foodinme/burgatron'
