source 'https://rubygems.org'

gem 'burgatron', github: 'foodinme/burgatron'
gem 'coffee-script'
gem 'haml'
gem 'json'
gem 'pg'
gem 'pry'
gem 'puma', '~> 6.1'
gem 'sass', '~> 3.3.0'
gem 'sequel'
gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'sinatra-contrib'

